name: Fvm Update
on: 
  schedule:
    - cron: "0 21 * * 1,4"
jobs:
  build:
    name: Check and Update fvm
    runs-on: macos-latest
    steps:
      - name: Get latest fvm release
        id: latest_release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const {data:release} = await github.repos.getLatestRelease({
              owner: "befovy",
              repo: "fvm",
            })
            console.log(release)
            return release.tag_name

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get local version
        id: local_version
        run: |
          VERSION=`grep version Formula/fvm.rb | head -n 1`
          VERSION=${VERSION##* }
          VERSION=${VERSION//\"}
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Update
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        run: |
          LOCAL_VERSION=${{steps.local_version.outputs.version}}
          LATEST_VERSION=${{steps.latest_release.outputs.result}}
          brew install --build-from-source Formula/fvm.rb
          sed -i.back "s/${LOCAL_VERSION}/$LATEST_VERSION/g" Formula/fvm.rb
          SOURCE_URL=https://github.com/befovy/fvm/archive/${LATEST_VERSION}.tar.gz
          wget $SOURCE_URL
          echo $SOURCE_URL
          SHA256=`shasum -a 256 ${LATEST_VERSION}.tar.gz`
          echo $SHA256
          SHA256=${SHA256% *}
          echo $SHA256
          SHA256=${SHA256// }
          sed -i -- "9s/.*/  sha256 \"${SHA256}\"/" Formula/fvm.rb
          cat Formula/fvm.rb
          brew uninstall fvm | echo "uninstall fvm"
          brew install --build-bottle ./Formula/fvm.rb
          brew tap befovy/taps
          cp -v Formula/fvm.rb /usr/local/Homebrew/Library/Taps/befovy/homebrew-taps/Formula/fvm.rb
          sed -i.back "33,40d;" Formula/fvm.rb 
          brew bottle fvm
          brew bottle --root-url https://github.com/befovy/homebrew-taps/releases/download/fvm-${LATEST_VERSION} fvm | tail -n 5 > bottle.txt
          cat bottle.txt
          cat Formula/fvm.rb bottle.txt > merge.txt
          echo end >> merge.txt
          cp merge.txt Formula/fvm.rb
          cat Formula/fvm.rb
          rm Formula/fvm.rb.back
          rm bottle.txt
          rm merge.txt

      - name: Commit files
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        run: |
          git config --local user.email "befovy@gmail.com"
          git config --local user.name "befvy"
          git add -u
          git commit -m "feat: fvm update version to ${{steps.latest_release.outputs.result}}" -a

      - name: Create new release
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: fvm-${{steps.latest_release.outputs.result}}
          release_name: Release fvm-${{steps.latest_release.outputs.result}}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        id: upload-linux-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fvm--${{steps.latest_release.outputs.result}}.catalina.bottle.tar.gz
          asset_name: fvm-${{steps.latest_release.outputs.result}}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

      - name: Push changes
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
