name: Fvm Update
on: [push]

jobs:
  build:
    name: Check and Update fvm
    runs-on: macos-latest
    steps:
      - name: Get Latest fvm release
        id: latest_release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const {data:release} = await github.repos.getLatestRelease({
              owner: "befovy",
              repo: "fvm",
            })
            console.log(release)
            return release.tag_name

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get Local Version
        id: local_version
        run: |
          VERSION=`grep version Formula/fvm.rb | head -n 1`
          VERSION=${VERSION##* }
          VERSION=${VERSION//\"}
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Update
        if: ${{ steps.latest_release.outputs.result != steps.local_version.outputs.version}}
        run: |
          LOCAL_VERSION=${{steps.local_version.outputs.version}}
          LATEST_VERSION=${{steps.latest_release.outputs.result}}
          sed -i -- "s/${LOCAL_VERSION}/$LATEST_VERSION/g" Formula/fvm.rb
          SOURCE_URL=https://github.com/befovy/fvm/archive/${LATEST_VERSION}.tar.gz
          wget $SOURCE_URL
          echo $SOURCE_URL
          SHA256=`shasum -a 256 ${LATEST_VERSION}.tar.gz`
          echo $SHA256
          SHA256=${SHA256% *}
          echo $SHA256
          SHA256=${SHA256// }
          sed -i -- "9s/.*/  sha256 \"${SHA256}\"/" Formula/fvm.rb
          cat Formula/fvm.rb
          brew install ./Formula/fvm.rb --build-bottle | echo "0"
          brew bottle fvm | echo "0"
